import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("data.csv")
print(data.dtypes)
print(data.head())
print(data.describe())
print(data.info())
data["Date_connexion"]=pd.to_datetime(data["Date_connexion"]) #force la conversion de la colonne "Date_connexion" en datetime
data["Mois"]=data["Date_connexion"].dt.month_name(locale="fr_FR") #ajoute une colonne "Mois" avec le nom du mois en français
print(data.head())
Moyenne=data.groupby("Utilisateur")["Duree_session"].mean()
print(f"la Moyene Par utulisateur  : {Moyenne}")
NbConnexion=data.groupby("Mois")["Date_connexion"].count()
print(f"le nombre de connexion par mois : {NbConnexion}")
LaPagePlusVisite=data.groupby("Page_principale_visitee")["Date_connexion"].count().idxmax()
print(f"la page la plus visitée est : {LaPagePlusVisite}")
Correlation=data["Duree_session"].corr(data["Note_satisfaction"])
print(f'la correlation  entre la  duree de session  et  la  note de satisfaction est  : {Correlation}')
plt.figure(figsize=(10, 6))
plt.hist(data['Note_satisfaction'], bins=10, color='blue', alpha=0.7)
plt.xlabel('note de satisfaction')
plt.ylabel('Nombre de sessions')
plt.title('Distribution des notes de satisfaction')
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(data["Date_connexion"],data["Mois"],color="red")
plt.xlabel("Date de connexion")
plt.ylabel("Mois")
plt.title("l’évolution des connexions par mois")
plt.show()
plt.figure(figsize=(10,5))
Pages=data['Page_principale_visitee'].value_counts()
Pages.plot(color='blue')
plt.xlabel('Pages principales visitées')
plt.ylabel('Nombre de visites')
plt.title('Nombre de visites par page principale')
plt.show()
plt.figure(figsize=(10,5))
Sessions=data['Duree_session'].value_counts()
plt.boxplot(Sessions)
plt.xlabel('Durée de session')
plt.ylabel('Nombre de sessions')
plt.title('Durée de session')
plt.show()
data.to_csv("data_cleaned.csv", index=False) #enregistre le dataframe nettoyé dans un nouveau fichier CSV